// This file is automatically generated. Do not edit it directly.
// Supabase is not used - using MongoDB instead
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Supabase client is disabled - MongoDB is used as the primary database
export const supabase = null;